/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bakery;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jsm college
 */
public class MDIForm extends javax.swing.JFrame {

    /**
     * Creates new form MDIForm
     */
    public MDIForm() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_master = new javax.swing.JMenu();
        mi_clients = new javax.swing.JMenuItem();
        mi_employee = new javax.swing.JMenuItem();
        mi_orders = new javax.swing.JMenuItem();
        mi_product = new javax.swing.JMenuItem();
        menu_stock = new javax.swing.JMenu();
        mi_freshStock = new javax.swing.JMenuItem();
        mi_snackStock = new javax.swing.JMenuItem();
        mi_viewstock = new javax.swing.JMenuItem();
        menu_billing = new javax.swing.JMenu();
        mi_custbill = new javax.swing.JMenuItem();
        menu_reports = new javax.swing.JMenu();
        mi_productsreport = new javax.swing.JMenuItem();
        mi_clientreport = new javax.swing.JMenuItem();
        mi_empreport = new javax.swing.JMenuItem();
        mi_orderreport = new javax.swing.JMenuItem();
        mi_stockreport = new javax.swing.JMenuItem();
        mi_salereport = new javax.swing.JMenuItem();
        mi_wastagereport = new javax.swing.JMenuItem();
        menu_setting = new javax.swing.JMenu();
        mi_user = new javax.swing.JMenuItem();
        mi_changepass = new javax.swing.JMenuItem();
        mi_aboutus = new javax.swing.JMenuItem();
        mi_exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        menu_master.setText("Master");
        menu_master.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        mi_clients.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mi_clients.setText("Clients");
        mi_clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_clientsActionPerformed(evt);
            }
        });
        menu_master.add(mi_clients);

        mi_employee.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mi_employee.setText("Employee");
        mi_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_employeeActionPerformed(evt);
            }
        });
        menu_master.add(mi_employee);

        mi_orders.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mi_orders.setText("Orders");
        mi_orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_ordersActionPerformed(evt);
            }
        });
        menu_master.add(mi_orders);

        mi_product.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mi_product.setText("Products");
        mi_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_productActionPerformed(evt);
            }
        });
        menu_master.add(mi_product);

        jMenuBar1.add(menu_master);

        menu_stock.setText("Stock");
        menu_stock.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        mi_freshStock.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mi_freshStock.setText("Fresh");
        mi_freshStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_freshStockActionPerformed(evt);
            }
        });
        menu_stock.add(mi_freshStock);

        mi_snackStock.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mi_snackStock.setText("Snacks");
        mi_snackStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_snackStockActionPerformed(evt);
            }
        });
        menu_stock.add(mi_snackStock);

        mi_viewstock.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mi_viewstock.setText("View Stock");
        mi_viewstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_viewstockActionPerformed(evt);
            }
        });
        menu_stock.add(mi_viewstock);

        jMenuBar1.add(menu_stock);

        menu_billing.setText("Billing");
        menu_billing.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        mi_custbill.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mi_custbill.setText("Customer bill");
        mi_custbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_custbillActionPerformed(evt);
            }
        });
        menu_billing.add(mi_custbill);

        jMenuBar1.add(menu_billing);

        menu_reports.setText("Reports");
        menu_reports.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        menu_reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_reportsActionPerformed(evt);
            }
        });

        mi_productsreport.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mi_productsreport.setText("Products");
        mi_productsreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_productsreportActionPerformed(evt);
            }
        });
        menu_reports.add(mi_productsreport);

        mi_clientreport.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mi_clientreport.setText("Clients");
        mi_clientreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_clientreportActionPerformed(evt);
            }
        });
        menu_reports.add(mi_clientreport);

        mi_empreport.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mi_empreport.setText("Employee");
        mi_empreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_empreportActionPerformed(evt);
            }
        });
        menu_reports.add(mi_empreport);

        mi_orderreport.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mi_orderreport.setText("Order");
        mi_orderreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_orderreportActionPerformed(evt);
            }
        });
        menu_reports.add(mi_orderreport);

        mi_stockreport.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mi_stockreport.setText("Stock");
        mi_stockreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_stockreportActionPerformed(evt);
            }
        });
        menu_reports.add(mi_stockreport);

        mi_salereport.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mi_salereport.setText("Sale");
        mi_salereport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_salereportActionPerformed(evt);
            }
        });
        menu_reports.add(mi_salereport);

        mi_wastagereport.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mi_wastagereport.setText("Wastage");
        mi_wastagereport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_wastagereportActionPerformed(evt);
            }
        });
        menu_reports.add(mi_wastagereport);

        jMenuBar1.add(menu_reports);

        menu_setting.setText("Settings");
        menu_setting.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_setting.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        menu_setting.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        menu_setting.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        mi_user.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mi_user.setText("User Management");
        mi_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_userActionPerformed(evt);
            }
        });
        menu_setting.add(mi_user);

        mi_changepass.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mi_changepass.setText("Change Password");
        mi_changepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_changepassActionPerformed(evt);
            }
        });
        menu_setting.add(mi_changepass);

        mi_aboutus.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mi_aboutus.setText("About Us");
        mi_aboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_aboutusActionPerformed(evt);
            }
        });
        menu_setting.add(mi_aboutus);

        mi_exit.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mi_exit.setText("Exit");
        mi_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_exitActionPerformed(evt);
            }
        });
        menu_setting.add(mi_exit);

        jMenuBar1.add(menu_setting);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_clientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_clientsActionPerformed
             new Client().setVisible(true);
    }//GEN-LAST:event_mi_clientsActionPerformed

    private void mi_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_employeeActionPerformed
       Employee e=new Employee();
       e.setVisible(true);
    }//GEN-LAST:event_mi_employeeActionPerformed

    private void mi_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_exitActionPerformed
         int y=JOptionPane.showConfirmDialog(this,"Do you want to cancel and exit the application ?","Confirm",0,2);
        if(y==0)
        {
            System.exit(0);
        }
        else
        {
            //Do nothing and stay on the same page;
        }
    }//GEN-LAST:event_mi_exitActionPerformed

    private void mi_freshStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_freshStockActionPerformed
         new FreshProducts().setVisible(true);          
    }//GEN-LAST:event_mi_freshStockActionPerformed

    private void mi_aboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_aboutusActionPerformed
        new AboutUs().setVisible(true);  
    }//GEN-LAST:event_mi_aboutusActionPerformed

    private void mi_ordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_ordersActionPerformed
       new Order().setVisible(true);
    }//GEN-LAST:event_mi_ordersActionPerformed

    private void mi_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_userActionPerformed
        new UserManagement().setVisible(true);
    }//GEN-LAST:event_mi_userActionPerformed

    private void mi_changepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_changepassActionPerformed
        new ChangePW().setVisible(true);
    }//GEN-LAST:event_mi_changepassActionPerformed

    private void mi_custbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_custbillActionPerformed
        new Customer_bill().setVisible(true);
    }//GEN-LAST:event_mi_custbillActionPerformed

    private void menu_reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_reportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_reportsActionPerformed

    private void mi_snackStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_snackStockActionPerformed
        new Snack().setVisible(true);  
    }//GEN-LAST:event_mi_snackStockActionPerformed

    private void mi_empreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_empreportActionPerformed
       new ReportEmployee().setVisible(true);
    }//GEN-LAST:event_mi_empreportActionPerformed

    private void mi_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_productActionPerformed
        new Products().setVisible(true);
    }//GEN-LAST:event_mi_productActionPerformed

    private void mi_orderreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_orderreportActionPerformed
        new ReportOrder().setVisible(true);
    }//GEN-LAST:event_mi_orderreportActionPerformed

    private void mi_wastagereportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_wastagereportActionPerformed
        new ReportWastage().setVisible(true);
    }//GEN-LAST:event_mi_wastagereportActionPerformed

    private void mi_salereportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_salereportActionPerformed
        new ReportSale().setVisible(true);
    }//GEN-LAST:event_mi_salereportActionPerformed

    private void mi_productsreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_productsreportActionPerformed
         new ReportProducts().setVisible(true);
    }//GEN-LAST:event_mi_productsreportActionPerformed

    private void mi_clientreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_clientreportActionPerformed
         new ReportClients().setVisible(true);
    }//GEN-LAST:event_mi_clientreportActionPerformed

    private void mi_viewstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_viewstockActionPerformed
        
    }//GEN-LAST:event_mi_viewstockActionPerformed

    private void mi_stockreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_stockreportActionPerformed
         new ViewStock().setVisible(true);
    }//GEN-LAST:event_mi_stockreportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                MDIForm mf=new MDIForm();
                mf.setTitle("MDI Form");
                mf.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menu_billing;
    private javax.swing.JMenu menu_master;
    javax.swing.JMenu menu_reports;
    private javax.swing.JMenu menu_setting;
    private javax.swing.JMenu menu_stock;
    private javax.swing.JMenuItem mi_aboutus;
    private javax.swing.JMenuItem mi_changepass;
    private javax.swing.JMenuItem mi_clientreport;
    private javax.swing.JMenuItem mi_clients;
    private javax.swing.JMenuItem mi_custbill;
    javax.swing.JMenuItem mi_employee;
    private javax.swing.JMenuItem mi_empreport;
    private javax.swing.JMenuItem mi_exit;
    private javax.swing.JMenuItem mi_freshStock;
    private javax.swing.JMenuItem mi_orderreport;
    private javax.swing.JMenuItem mi_orders;
    javax.swing.JMenuItem mi_product;
    private javax.swing.JMenuItem mi_productsreport;
    private javax.swing.JMenuItem mi_salereport;
    private javax.swing.JMenuItem mi_snackStock;
    private javax.swing.JMenuItem mi_stockreport;
    javax.swing.JMenuItem mi_user;
    private javax.swing.JMenuItem mi_viewstock;
    private javax.swing.JMenuItem mi_wastagereport;
    // End of variables declaration//GEN-END:variables

}
