package bakery;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

public class ReportProducts extends javax.swing.JFrame {

    Connection con;
    PreparedStatement ps;
    Statement st;
    ResultSet rs;

    public ReportProducts() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
         try {
                con = ConnectString.ConnectDb();
                st = con.createStatement();
                rs = st.executeQuery("select p_id from Product");
                while (rs.next()) {
                    cmb_id1.addItem(rs.getString(1));
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Product Data Does Not Exit", "INFORMATION", JOptionPane.ERROR_MESSAGE);
            }
        //loadTable();
    }

    void Header() {
        tbl_product.getColumnModel().getColumn(0).setHeaderValue("Product ID");
        tbl_product.getColumnModel().getColumn(1).setHeaderValue("Product Name");
        tbl_product.getColumnModel().getColumn(2).setHeaderValue("Category");
        tbl_product.getColumnModel().getColumn(3).setHeaderValue("Sub Category");
        tbl_product.getColumnModel().getColumn(4).setHeaderValue("Type");
        tbl_product.getColumnModel().getColumn(5).setHeaderValue("Unit Of Measurment");
        tbl_product.getColumnModel().getColumn(6).setHeaderValue("Rate");
    }

    void loadTable() {
        try {
            con = ConnectString.ConnectDb();
            String sql = "select * from Product";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            tbl_product.setModel(DbUtils.resultSetToTableModel(rs));
            Header();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_product = new javax.swing.JTable();
        btn_print = new javax.swing.JButton();
        btn_showall = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmb_type = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmb_cat = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cmb_subcat = new javax.swing.JComboBox();
        cmb_id1 = new javax.swing.JComboBox();
        btn_back5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Products Report");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search By Id :");

        tbl_product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_product);

        btn_print.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        btn_showall.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_showall.setText("Show All");
        btn_showall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showallActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Search  By Type :");

        cmb_type.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmb_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<<Select>>", "Egg", "Eggless" }));
        cmb_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_typeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search By Category :");

        cmb_cat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmb_cat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<<Select>>", "Fresh", "Snack" }));
        cmb_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_catActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Search  By Subcategory :");

        cmb_subcat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmb_subcat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<<Select>>", "Cake", "Pastry", "Cupcake", "Cookie", "Bread", "Chips", "Other" }));
        cmb_subcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_subcatActionPerformed(evt);
            }
        });

        cmb_id1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmb_id1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<<Select>>" }));
        cmb_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_id1ActionPerformed(evt);
            }
        });

        btn_back5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources2/home.png"))); // NOI18N
        btn_back5.setText("Back to home");
        btn_back5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_cat, 0, 148, Short.MAX_VALUE)
                            .addComponent(cmb_id1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_subcat, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmb_type, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btn_showall)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_print)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_back5)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(cmb_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(btn_showall)
                                .addComponent(btn_print)
                                .addComponent(cmb_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(cmb_subcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(cmb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btn_back5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        MessageFormat header = new MessageFormat("Client Report");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
            tbl_product.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("cnnot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_showallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showallActionPerformed
        loadTable();
    }//GEN-LAST:event_btn_showallActionPerformed

    private void cmb_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_typeActionPerformed
 if (cmb_type.getSelectedIndex() == 0) {
            loadTable();
        } else if(cmb_type.getSelectedIndex()==1){
            try {

                con = ConnectString.ConnectDb();
                st = con.createStatement();
                String sql = "select * from Product where type='"+"Egg"+"'";
                rs = st.executeQuery(sql);
                tbl_product.setModel(DbUtils.resultSetToTableModel(rs));
                Header();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
 else if(cmb_type.getSelectedIndex()==2){
            try {

                con = ConnectString.ConnectDb();
                st = con.createStatement();
                String sql = "select * from Product where type='"+"Eggless"+"'";
                rs = st.executeQuery(sql);
                tbl_product.setModel(DbUtils.resultSetToTableModel(rs));
                Header();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_cmb_typeActionPerformed

    private void cmb_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_catActionPerformed
        if (cmb_cat.getSelectedIndex() == 0) {
            loadTable();
        } else if(cmb_cat.getSelectedIndex()==1){
            try {

                con = ConnectString.ConnectDb();
                st = con.createStatement();
                String sql = "select * from Product where cat='"+"Fresh"+"'";
                rs = st.executeQuery(sql);
                tbl_product.setModel(DbUtils.resultSetToTableModel(rs));
                Header();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
 else if(cmb_cat.getSelectedIndex()==2){
            try {

                con = ConnectString.ConnectDb();
                st = con.createStatement();
                String sql = "select * from Product where cat='"+"Snack"+"'";
                rs = st.executeQuery(sql);
                tbl_product.setModel(DbUtils.resultSetToTableModel(rs));
                Header();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_cmb_catActionPerformed

    private void cmb_subcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_subcatActionPerformed
        if (cmb_subcat.getSelectedIndex() == 0) {
            loadTable();
        } else if(cmb_subcat.getSelectedIndex()==1){
            try {

                con = ConnectString.ConnectDb();
                st = con.createStatement();
                String sql = "select * from Product where subcat='"+"Cake"+"'";
                rs = st.executeQuery(sql);
                tbl_product.setModel(DbUtils.resultSetToTableModel(rs));
                Header();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
 else if(cmb_subcat.getSelectedIndex()==2){
            try {

                con = ConnectString.ConnectDb();
                st = con.createStatement();
                String sql = "select * from Product where subcat='"+"Pastry"+"'";
                rs = st.executeQuery(sql);
                tbl_product.setModel(DbUtils.resultSetToTableModel(rs));
                Header();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
        else if(cmb_subcat.getSelectedIndex()==3){
            try {

                con = ConnectString.ConnectDb();
                st = con.createStatement();
                String sql = "select * from Product where subcat='"+"Cupcake"+"'";
                rs = st.executeQuery(sql);
                tbl_product.setModel(DbUtils.resultSetToTableModel(rs));
                Header();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
 else if(cmb_subcat.getSelectedIndex()==4){
            try {

                con = ConnectString.ConnectDb();
                st = con.createStatement();
                String sql = "select * from Product where subcat='"+"Cookie"+"'";
                rs = st.executeQuery(sql);
                tbl_product.setModel(DbUtils.resultSetToTableModel(rs));
                Header();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
        else if(cmb_subcat.getSelectedIndex()==5){
            try {

                con = ConnectString.ConnectDb();
                st = con.createStatement();
                String sql = "select * from Product where subcat='"+"Bread"+"'";
                rs = st.executeQuery(sql);
                tbl_product.setModel(DbUtils.resultSetToTableModel(rs));
                Header();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
 else if(cmb_subcat.getSelectedIndex()==6){
            try {

                con = ConnectString.ConnectDb();
                st = con.createStatement();
                String sql = "select * from Product where subcat='"+"Chips"+"'";
                rs = st.executeQuery(sql);
                tbl_product.setModel(DbUtils.resultSetToTableModel(rs));
                Header();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
        else if(cmb_subcat.getSelectedIndex()==7){
            try {

                con = ConnectString.ConnectDb();
                st = con.createStatement();
                String sql = "select * from Product where subcat='"+"Other"+"'";
                rs = st.executeQuery(sql);
                tbl_product.setModel(DbUtils.resultSetToTableModel(rs));
                Header();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
       
    }//GEN-LAST:event_cmb_subcatActionPerformed

    private void cmb_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_id1ActionPerformed
         if (cmb_id1.getSelectedIndex() == 0) {
            loadTable();
        } else {
            try {

                con = ConnectString.ConnectDb();
                st = con.createStatement();
                String sql = "select * from Product where p_id='" + cmb_id1.getSelectedItem() + "'";
                rs = st.executeQuery(sql);
                tbl_product.setModel(DbUtils.resultSetToTableModel(rs));
                Header();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_cmb_id1ActionPerformed

    private void btn_back5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_back5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back5;
    private javax.swing.JButton btn_back7;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_showall;
    private javax.swing.JComboBox cmb_cat;
    private javax.swing.JComboBox cmb_id1;
    private javax.swing.JComboBox cmb_subcat;
    private javax.swing.JComboBox cmb_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_product;
    // End of variables declaration//GEN-END:variables
}
